spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: -1
      retries: 3
      properties:
        enable.idempotence: true
        max.request.size: 10485760
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 1000
      max-poll-records: 15
      auto-offset-reset: latest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: roon-kafka-practice
      properties:
        fetch.max.bytes: 10485760
        max.partition.fetch.bytes: 10485760

    template:
      default-topic: sample-topic

---
spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: localhost:49169

---
spring:
  config:
    activate:
      on-profile: "dev | real"

  kafka:
    bootstrap-servers:
