spring:
  kafka:
    # 이렇게 프로퍼티로 설정하면 kafka producer 설정 자동구성되는듯
    # 별도의 @Bean으로 producer factory, producer config, kafkaTemplate 설정할 필요없음!!
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: roon.practice.sample.kafka.infra.serialization.CustomSerializer
      acks: -1
      retries: 3
      properties:
        enable.idempotence: true
        max.request.size: 10485760
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 1000
      max-poll-records: 15
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: roon.practice.sample.kafka.infra.serialization.CustomDeserializer
      group-id: roon-kafka-practice
      properties:
        fetch.max.bytes: 10485760
        max.partition.fetch.bytes: 10485760

    template:
      default-topic: sample-topic

---
spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: localhost:49159

---
spring:
  config:
    activate:
      on-profile: "dev | real"

  kafka:
    bootstrap-servers:
